modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="boudicas_mod"
version="1.0.0"
displayName="Boudica`s Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="AaronAnehasseRomera, MCreator"

[[dependencies.boudicas_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




